name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta_platform
        uses: docker/metadata-action@v5
        with:
          images: |
            nauedu/nau-analytics-external-data-product
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build Docker image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Docker/Dockerfile
          load: true
          tags: ${{ steps.meta_platform.outputs.tags }}
          labels: ${{ steps.meta_platform.outputs.labels }}

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push with branch name tag
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          set -x
          IMAGE_NAME="nauedu/nau-analytics-external-data-product"
          BRANCH_TAG="${GITHUB_REF_NAME}"
      
          # Tag the image with the branch name
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$BRANCH_TAG
          docker push $IMAGE_NAME:$BRANCH_TAG
      
          echo "✅ Pushed branch tag '$BRANCH_TAG' on https://hub.docker.com/r/$IMAGE_NAME/tags"

      - name: Docker push SHA tag if branch is main
        if: ${{ github.ref_name == 'main' && github.event_name != 'pull_request' }}
        run: |
          set -x
          IMAGE_NAME="nauedu/nau-analytics-external-data-product"
          SHA_TAG=$(echo $GITHUB_SHA | head -c7)

          docker tag $IMAGE_NAME:$SHA_TAG $IMAGE_NAME:$SHA_TAG
          docker push $IMAGE_NAME:$SHA_TAG

          echo "✅ Pushed SHA tag $SHA_TAG for main branch on https://hub.docker.com/r/$IMAGE_NAME/tags"
